project:
  title: "Slides for Statistical Analysis in Sociology"
  pre-render:
    - scripts/check_packages.R
  render:
    - slides*.qmd
    - index.qmd
  output-dir: _slides

subtitle: "Sociology 312/412/512, University of Oregon"
author: "Aaron Gullickson"
execute:
  eval: true
  echo: true
  warning: false
  error: false
  fig-height: 11
  freeze: auto
format:
  revealjs:
    theme: [default, custom.scss]
    chalkboard: true
    preview-links: true
    incremental: true
    smaller: false
    background-transition: concave
    fig-align: center
    highlight-style: tango
    code-line-numbers: false
    html-math-method: mathjax
    footer: "Sociology 312/412/512, University of Oregon"
revealjs-plugins:
  - codefocus
editor: source
title-slide-attributes:
    data-background-image: "images/markus-spiske-666905-unsplash.jpg"
    data-background-size: cover
