project:
  title: "Slides for Statistical Analysis in Sociology"
  pre-render:
    - scripts/check_packages.R
  render:
    - slides*.qmd
    - index.qmd
  output-dir: _slides

subtitle: "Sociology 312/412/512, University of Oregon"
author: "Aaron Gullickson"
execute:
  eval: true
  echo: true
  warning: false
  error: false
  # the default size here is set up for half-width figures as most
  # figures are in a column. For full-width figures change asp to
  # 0.5625. For half-width figures with a title use asp of 1.1
  out-width: "100%"
  fig-asp: 1.2
  freeze: auto
format:
  revealjs:
    theme: [default, custom.scss]
    fig-format: svg
    chalkboard: true
    preview-links: true
    incremental: true
    smaller: false
    background-transition: concave
    fig-align: center
    highlight-style: tango
    code-line-numbers: false
    html-math-method: mathjax
    footer: "Sociology 312/412/512, University of Oregon"
revealjs-plugins:
  - codefocus
editor: source
title-slide-attributes:
    data-background-image: "images/markus-spiske-666905-unsplash.jpg"
    data-background-size: cover
