#load(url("https://github.com/AaronGullickson/stat_data/raw/main/output/titanic.RData"))
#load(url("https://github.com/AaronGullickson/stat_data/raw/main/output/movies.RData"))
#load(url("https://github.com/AaronGullickson/stat_data/raw/main/output/sex.RData"))
#load(url("https://github.com/AaronGullickson/stat_data/raw/main/output/popularity.RData"))
#load(url("https://github.com/AaronGullickson/stat_data/raw/main/output/addhealth.RData"))
#load(url("https://github.com/AaronGullickson/stat_data/raw/main/output/earnings.RData"))
#load(url("https://github.com/AaronGullickson/stat_data/raw/main/output/crimes.RData"))
#load(url("https://github.com/AaronGullickson/stat_data/raw/main/output/politics.RData"))

load("../stat_data/output/titanic.RData")
load("../stat_data/output/movies.RData")
load("../stat_data/output/sex.RData")
load("../stat_data/output/popularity.RData")
load("../stat_data/output/addhealth.RData")
load("../stat_data/output/earnings.RData")
load("../stat_data/output/crimes.RData")
load("../stat_data/output/politics.RData")
